### ISSUE TITLE
Uncaught SyntaxError: Invalid or unexpected token

### ISSUE THREAD

**Issue by andres-lowrie** [AtomLinter/linter-rust#115]
1. Start atom from cli `atom /some/path`
2. Expect error

**Atom**: 1.21.1 x64
**Electron**: 1.6.15
**OS**: Ubuntu 17.04
**Thrown From**: [linter-rust](https://github.com/AtomLinter/linter-rust) package 0.8.0

### Stack Trace

Uncaught SyntaxError: Invalid or unexpected token

```
At /usr/share/atom/resources/app/src/native-compile-cache.js:97

SyntaxError: Invalid or unexpected token
    at Module.get_Module._compile (/usr/share/atom/resources/app/src/native-compile-cache.js:94:52)
    at Object.value [as .js] (/usr/share/atom/resources/app/src/compile-cache.js:239:29)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (/app.asar/static/index.js:47:45)
    at require (/usr/share/atom/resources/app/src/native-compile-cache.js:66:33)
    at /packages/linter-rust/node_modules/atom-package-deps/lib/helpers.js:135:13)
    at /packages/linter-rust/node_modules/atom-package-deps/lib/helpers.js:180:3)
    at Module.get_Module._compile (/usr/share/atom/resources/app/src/native-compile-cache.js:106:36)
    at Object.value [as .js] (/usr/share/atom/resources/app/src/compile-cache.js:239:29)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (/app.asar/static/index.js:47:45)
    at require (/usr/share/atom/resources/app/src/native-compile-cache.js:66:33)
    at /packages/linter-rust/node_modules/atom-package-deps/lib/index.js:55:16)
    at /packages/linter-rust/node_modules/atom-package-deps/lib/index.js:84:3)
    at Module.get_Module._compile (/usr/share/atom/resources/app/src/native-compile-cache.js:106:36)
    at Object.value [as .js] (/usr/share/atom/resources/app/src/compile-cache.js:239:29)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (/app.asar/static/index.js:47:45)
    at require (/usr/share/atom/resources/app/src/native-compile-cache.js:66:33)
    at linterDepsInstall (/packages/linter/lib/index.js:80:9)
```

### Non-Core Packages

```
atom-beautify 0.30.5 
atom-handlebars 1.3.0 
atom-underscore 0.1.3 
busy-signal 1.4.3 
docblockr 0.11.0 
easy-motion-redux 1.1.1 
emmet 2.4.3 
go-debug 1.5.2 
go-plus 5.5.5 
go-signature-statusbar 1.2.3 
hard-wrap 1.1.0 
hey-pane 1.0.0 
hyperclick 0.1.5 
intentions 1.1.5 
language-rust 0.4.12 
language-vue 0.23.1 
linter 2.2.0 
linter-csslint 2.0.0 
linter-eslint 8.2.1 
linter-rust 0.8.0 
linter-sass-lint 1.7.6 
linter-tslint 1.7.0 
linter-ui-default 1.6.10 
octocat-syntax 1.3.1 
racer 0.20.0 
relative-numbers 0.8.0 
spacemacs-evil-keys 0.2.0 
vim-mode-plus 1.5.0 
vim-mode-plus-keymaps-for-surround 0.2.1 
vim-mode-plus-move-to-symbols 0.3.0 
zentabs 0.8.8 
```

**Comment by Arcanemagus** [comment]
Looks like this was an issue in one of the sub-dependencies of `atom-package-deps`, closing for now.
