### ISSUE TITLE
Failed to activate: Cannot find module: @babel/runtime/core-js/object/create

### ISSUE THREAD

**Issue by Navigatron** [AtomLinter/linter-rust#141]
Steps to Reproduce:

1. Remove atom entirely
    - `sudo pacman -R atom`
    - Other commands removing config files and directories
2. Re-Install Atom
3. Start Atom
4. Search for and install linter-rust
    - Error is thrown
    - Asks to install dependencies
5. Select Yes, install all dependencies
6. Close atom, re-open, same error occurs once more.

Note: The notification states "This issue has already been reported". Selecting "View Issue" opens issue #19 

Selecting "Copy error report to clipboard" yields the following:

**Atom**: 1.33.1 x64
**Electron**: 3.0.13
**OS**: linux 4.20.0-arch1-1-ARCH
**Thrown From**: [linter-rust](https://github.com/AtomLinter/linter-rust) package 0.9.0

### Stack Trace

Failed to activate the linter-rust package

```
At Cannot find module '@babel/runtime/core-js/object/create'

Error: Cannot find module '@babel/runtime/core-js/object/create'
    at Module._resolveFilename (internal/modules/cjs/loader.js:602:15)
    at Module._resolveFilename (/usr/lib/electron/resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.Module._resolveFilename (/usr/lib/atom/src/module-cache.js:283:28)
    at Function.Module._load (internal/modules/cjs/loader.js:528:25)
    at Module.require (internal/modules/cjs/loader.js:658:17)
    at require (/usr/lib/atom/src/native-compile-cache.js:47:27)
    at /packages/linter-rust/node_modules/xregexp/lib/xregexp.js:10:38)
    at /packages/linter-rust/node_modules/xregexp/lib/xregexp.js:2014:3)
    at Module._compile (/usr/lib/atom/src/native-compile-cache.js:87:30)
    at Object.value [as .js] (/usr/lib/atom/src/compile-cache.js:235:23)
    at Module.load (internal/modules/cjs/loader.js:620:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:559:12)
    at Function.Module._load (internal/modules/cjs/loader.js:551:3)
    at Module.require (internal/modules/cjs/loader.js:658:17)
    at require (/usr/lib/atom/src/native-compile-cache.js:47:27)
    at /packages/linter-rust/node_modules/xregexp/lib/index.js:10:39)
    at /packages/linter-rust/node_modules/xregexp/lib/index.js:36:3)
    at Module._compile (/usr/lib/atom/src/native-compile-cache.js:87:30)
    at Object.value [as .js] (/usr/lib/atom/src/compile-cache.js:235:23)
    at Module.load (internal/modules/cjs/loader.js:620:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:559:12)
    at Function.Module._load (internal/modules/cjs/loader.js:551:3)
    at Module.require (internal/modules/cjs/loader.js:658:17)
    at require (/usr/lib/atom/src/native-compile-cache.js:47:27)
    at /packages/linter-rust/lib/linter-rust.coffee:7:11)
    at /packages/linter-rust/lib/linter-rust.coffee:1:1)
    at /packages/linter-rust/lib/linter-rust.coffee:1:1)
    at Module._compile (/usr/lib/atom/src/native-compile-cache.js:87:30)
    at Object.value [as .coffee] (/usr/lib/atom/src/compile-cache.js:235:23)
    at Module.load (internal/modules/cjs/loader.js:620:32)
```

### Commands

```
     -0:27.9.0 settings-view:open (atom-pane.pane.active)
```

### Non-Core Packages

```
linter-rust 0.9.0 
```
## Second error

After the dependencies are installed and atom is re-started, the following sections change:

### Commands

```
```

### Non-Core Packages

```
busy-signal 2.0.0 
intentions 1.1.5 
language-rust 0.4.12 
linter 2.2.0 
linter-rust 0.9.0 
linter-ui-default 1.7.1 
```

**Comment by Arcanemagus** [comment]
Can you try re-installing the package? Usually missing dependencies are a bug in `apm` that we have no control over here.
