### ISSUE TITLE
Failed to activate the linter-rust package

### ISSUE THREAD

**Issue by markgeek** [AtomLinter/linter-rust#19]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.0.0
**System**: Ubuntu 15.04
**Thrown From**: [linter-rust](https://github.com/AtomLinter/linter-rust) package, v0.2.0

### Stack Trace

Failed to activate the linter-rust package

```
At Cannot read property 'path' of undefined

TypeError: Cannot read property 'path' of undefined
    at Object.<anonymous> (/home/lizhe/.atom/packages/linter-rust/lib/linter-rust.coffee:5:56)
    at Object.<anonymous> (/home/lizhe/.atom/packages/linter-rust/lib/linter-rust.coffee:116:4)
    at Module._compile (module.js:452:26)
    at Object.requireCoffeeScript (/opt/atom/resources/app.asar/node_modules/coffee-cash/lib/coffee-cash.js:85:19)
    at Module.load (module.js:347:32)
    at Function.Module._load (module.js:302:12)
    at Module.require (module.js:357:17)
    at require (module.js:376:17)
    at Object.module.exports.provideLinter (/home/lizhe/.atom/packages/linter-rust/lib/init.coffee:69:20)
    at Package.module.exports.Package.activateServices (/opt/atom/resources/app.asar/src/package.js:369:69)
```

### Commands

```
```

### Config

```json
{
  "core": {
    "ignoredNames": [
      ".git"
    ],
    "autoHideMenuBar": true
  }
}
```

### Installed Packages

```coffee
# User
file-icons, v1.5.8
highlight-selected, v0.10.1
linter-rust, v0.2.0
minimap, v4.10.1
minimap-git-diff, v4.1.3
minimap-highlight-selected, v4.3.0
pretty-json, v0.4.1

# Dev
No dev packages
```

**Comment by gmist** [comment]
Try to install the main package ```linter```
``` shell
apm install linter
```
or through Atom GUI (Preferences->Install). Also you need to install [```language-rust```](https://github.com/zargony/atom-language-rust) package.

**Comment by yvan-sraka** [comment]
I confirm that the command fix the issue.

Maybe it would be better to push a more user-friendly notification?

**Comment by colin-kiegel** [comment]
:+1: for user-friendly notifications :-)

**Comment by markgeek** [comment]
@gmist thanks, and it's really better to have a user-freindly notifications.

**Comment by steelbrain** [comment]
@gmist Be advised that the linter helpers have been published as an npm module https://npmjs.org/package/atom-linter
