### ISSUE TITLE
Error When Building with Language Rust Enabled

### ISSUE THREAD

**Issue by yeliknewo** [AtomLinter/linter-rust#67]
[Enter steps to reproduce below:]

1. Install Atom
2. Install Linter Rust
3. Install cargo build and build
3. Restart Atom
4. Build Any Project

Only errors the first time you build from each file. Error goes away when you disable language rust. When you renable language rust you can error from each file that you build from again.

**Atom Version**: 1.9.8
**System**: Ubuntu 16.04.1
**Thrown From**: [linter-rust](https://github.com/AtomLinter/linter-rust) package, v0.5.2

### Stack Trace

Uncaught ReferenceError: handle is not defined

```
At /home/yelikubuntu/.atom/packages/linter-rust/lib/linter-rust.coffee:37

ReferenceError: handle is not defined
    at stderr (/home/yelikubuntu/.atom/packages/linter-rust/lib/linter-rust.coffee:37:11)
    at Socket.<anonymous> (/usr/share/atom/resources/app.asar/src/buffered-process.js:87:13)
    at emitOne (events.js:90:13)
    at Socket.emit (events.js:182:7)
    at readableAddChunk (_stream_readable.js:153:18)
    at Socket.Readable.push (_stream_readable.js:111:10)
    at Pipe.onread (net.js:531:20)
```

### Commands

```
  4x -2:56.3.0 core:backspace (atom-text-editor#editor.tabLength.editor.mini.is-focused)
     -2:55.2.0 core:confirm (atom-text-editor#editor.tabLength.editor.mini.is-focused)
 58x -1:59.9.0 core:backspace (atom-text-editor#racer.racerBinPath.editor.mini.is-focused)
  2x -0:50.9.0 core:paste (div.package-detail.panels-item)
  2x -0:45.9.0 core:move-left (atom-text-editor#racer.rustSrcPath.editor.mini.is-focused)
 17x -0:45.3.0 core:delete (atom-text-editor#racer.rustSrcPath.editor.mini.is-focused)
  2x -0:41.5.0 core:backspace (atom-text-editor#racer.rustSrcPath.editor.mini.is-focused)
  2x -0:38.2.0 core:save (atom-text-editor#racer.rustSrcPath.editor.mini.is-focused)
```

### Config

```json
{}
```

### Installed Packages

```coffee
# User
atom-language-rust, v0.8.1 (active)
autocomplete-glsl, v0.2.3 (active)
build-cargo, v0.16.0 (active)
language-glsl, v2.0.1 (active)
language-rust, v0.4.6 (active)
linter, v1.11.16 (active)
linter-rust, v0.5.2 (active)
racer, v0.20.0 (active)
rust-api-docs-helper, v0.5.1 (active)
atom-dark-syntax, v0.27.0 (inactive)
atom-dark-ui, v0.51.0 (inactive)
atom-light-syntax, v0.28.0 (inactive)
atom-light-ui, v0.43.0 (inactive)
base16-tomorrow-dark-theme, v1.1.0 (inactive)
base16-tomorrow-light-theme, v1.1.1 (inactive)
one-dark-ui, v1.3.2 (active)
one-light-ui, v1.3.2 (inactive)
one-dark-syntax, v1.2.0 (active)
one-light-syntax, v1.2.0 (inactive)
solarized-dark-syntax, v1.0.2 (inactive)
solarized-light-syntax, v1.0.2 (inactive)
about, v1.5.2 (active)
archive-view, v0.61.1 (active)
autocomplete-atom-api, v0.10.0 (active)
autocomplete-css, v0.11.1 (active)
autocomplete-html, v0.7.2 (active)
autocomplete-plus, v2.31.0 (active)
autocomplete-snippets, v1.11.0 (active)
autoflow, v0.27.0 (inactive)
autosave, v0.23.1 (active)
background-tips, v0.26.0 (active)
bookmarks, v0.41.0 (active)
bracket-matcher, v0.82.1 (active)
command-palette, v0.38.0 (inactive)
deprecation-cop, v0.54.1 (active)
dev-live-reload, v0.47.0 (active)
encoding-selector, v0.22.0 (active)
exception-reporting, v0.39.0 (active)
fuzzy-finder, v1.3.0 (active)
git-diff, v1.1.0 (active)
find-and-replace, v0.198.0 (inactive)
go-to-line, v0.31.0 (inactive)
grammar-selector, v0.48.1 (active)
image-view, v0.58.0 (active)
incompatible-packages, v0.26.1 (active)
keybinding-resolver, v0.35.0 (active)
line-ending-selector, v0.5.0 (active)
link, v0.31.1 (inactive)
markdown-preview, v0.158.0 (active)
metrics, v0.53.1 (active)
notifications, v0.64.1 (active)
open-on-github, v1.2.0 (inactive)
package-generator, v1.0.0 (inactive)
settings-view, v0.238.2 (active)
snippets, v1.0.2 (active)
spell-check, v0.67.1 (active)
status-bar, v1.4.1 (active)
styleguide, v0.46.0 (active)
symbols-view, v0.113.0 (inactive)
tabs, v0.98.1 (active)
timecop, v0.33.1 (active)
tree-view, v0.208.0 (active)
update-package-dependencies, v0.10.0 (active)
welcome, v0.34.0 (active)
whitespace, v0.32.2 (active)
wrap-guide, v0.38.1 (active)
language-c, v0.52.1 (active)
language-clojure, v0.21.0 (active)
language-coffee-script, v0.47.0 (active)
language-csharp, v0.12.1 (active)
language-css, v0.36.2 (active)
language-gfm, v0.86.0 (active)
language-git, v0.13.0 (active)
language-go, v0.42.0 (active)
language-html, v0.44.1 (active)
language-hyperlink, v0.16.0 (active)
language-java, v0.22.0 (active)
language-javascript, v0.119.0 (active)
language-json, v0.18.0 (active)
language-less, v0.29.3 (active)
language-make, v0.22.2 (active)
language-mustache, v0.13.0 (active)
language-objective-c, v0.15.1 (active)
language-perl, v0.35.0 (active)
language-php, v0.37.0 (active)
language-property-list, v0.8.0 (active)
language-python, v0.45.0 (active)
language-ruby, v0.68.5 (active)
language-ruby-on-rails, v0.25.0 (active)
language-sass, v0.52.0 (active)
language-shellscript, v0.22.3 (active)
language-source, v0.9.0 (active)
language-sql, v0.21.1 (active)
language-text, v0.7.1 (active)
language-todo, v0.28.0 (active)
language-toml, v0.18.0 (active)
language-xml, v0.34.8 (active)
language-yaml, v0.26.0 (active)

# Dev
No dev packages
```

**Comment by yeliknewo** [comment]
Nevermind It seems to happen when the language-rust package isn't installed

**Comment by wraithbb** [comment]
The same problem as above. Installing or reinstalling language-rust doesn't solve the problem.

**Atom Version**: 1.9.8
**System**: Ubuntu 16.04.1
**Thrown From**: [linter-rust](https://github.com/AtomLinter/linter-rust) package, v0.5.2


### Stack Trace

Uncaught ReferenceError: handle is not defined

```
At /home/tku/.atom/packages/linter-rust/lib/linter-rust.coffee:37

ReferenceError: handle is not defined
    at stderr (/home/tku/.atom/packages/linter-rust/lib/linter-rust.coffee:37:11)
    at Socket.<anonymous> (/usr/share/atom/resources/app.asar/src/buffered-process.js:87:13)
    at emitOne (events.js:90:13)
    at Socket.emit (events.js:182:7)
    at readableAddChunk (_stream_readable.js:153:18)
    at Socket.Readable.push (_stream_readable.js:111:10)
    at Pipe.onread (net.js:531:20)
```

### Commands

```
     -0:00.2.0 core:save (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {},
  "linter-rust": {}
}
```

### Installed Packages

```coffee
# User
atom-beautify, v0.29.10 (active)
build, v0.65.0 (active)
build-cargo, v0.16.0 (active)
busy, v0.6.0 (active)
language-rust, v0.4.6 (active)
linter, v1.11.16 (active)
linter-rust, v0.5.2 (active)
local-history, v3.4.1 (active)
racer, v0.20.0 (active)
atom-dark-syntax, v0.27.0 (inactive)
atom-dark-ui, v0.51.0 (inactive)
atom-light-syntax, v0.28.0 (inactive)
atom-light-ui, v0.43.0 (inactive)
base16-tomorrow-dark-theme, v1.1.0 (inactive)
base16-tomorrow-light-theme, v1.1.1 (inactive)
one-dark-ui, v1.3.2 (active)
one-light-ui, v1.3.2 (inactive)
one-dark-syntax, v1.2.0 (active)
one-light-syntax, v1.2.0 (inactive)
solarized-dark-syntax, v1.0.2 (inactive)
solarized-light-syntax, v1.0.2 (inactive)
about, v1.5.2 (active)
archive-view, v0.61.1 (active)
autocomplete-atom-api, v0.10.0 (active)
autocomplete-css, v0.11.1 (active)
autocomplete-html, v0.7.2 (active)
autocomplete-plus, v2.31.0 (active)
autocomplete-snippets, v1.11.0 (active)
autoflow, v0.27.0 (inactive)
autosave, v0.23.1 (active)
background-tips, v0.26.0 (active)
bookmarks, v0.41.0 (active)
bracket-matcher, v0.82.1 (active)
command-palette, v0.38.0 (inactive)
deprecation-cop, v0.54.1 (active)
dev-live-reload, v0.47.0 (active)
encoding-selector, v0.22.0 (active)
exception-reporting, v0.39.0 (active)
fuzzy-finder, v1.3.0 (active)
git-diff, v1.1.0 (active)
find-and-replace, v0.198.0 (inactive)
go-to-line, v0.31.0 (inactive)
grammar-selector, v0.48.1 (active)
image-view, v0.58.0 (active)
incompatible-packages, v0.26.1 (active)
keybinding-resolver, v0.35.0 (active)
line-ending-selector, v0.5.0 (active)
link, v0.31.1 (inactive)
markdown-preview, v0.158.0 (active)
metrics, v0.53.1 (active)
notifications, v0.64.1 (active)
open-on-github, v1.2.0 (inactive)
package-generator, v1.0.0 (inactive)
settings-view, v0.238.2 (active)
snippets, v1.0.2 (active)
spell-check, v0.67.1 (active)
status-bar, v1.4.1 (active)
styleguide, v0.46.0 (active)
symbols-view, v0.113.0 (inactive)
tabs, v0.98.1 (active)
timecop, v0.33.1 (active)
tree-view, v0.208.0 (active)
update-package-dependencies, v0.10.0 (active)
welcome, v0.34.0 (active)
whitespace, v0.32.2 (active)
wrap-guide, v0.38.1 (active)
language-c, v0.52.1 (active)
language-clojure, v0.21.0 (active)
language-coffee-script, v0.47.0 (active)
language-csharp, v0.12.1 (active)
language-css, v0.36.2 (active)
language-gfm, v0.86.0 (active)
language-git, v0.13.0 (active)
language-go, v0.42.0 (active)
language-html, v0.44.1 (active)
language-hyperlink, v0.16.0 (active)
language-java, v0.22.0 (active)
language-javascript, v0.119.0 (active)
language-json, v0.18.0 (active)
language-less, v0.29.3 (active)
language-make, v0.22.2 (active)
language-mustache, v0.13.0 (active)
language-objective-c, v0.15.1 (active)
language-perl, v0.35.0 (active)
language-php, v0.37.0 (active)
language-property-list, v0.8.0 (active)
language-python, v0.45.0 (active)
language-ruby, v0.68.5 (active)
language-ruby-on-rails, v0.25.0 (active)
language-sass, v0.52.0 (active)
language-shellscript, v0.22.3 (active)
language-source, v0.9.0 (active)
language-sql, v0.21.1 (active)
language-text, v0.7.1 (active)
language-todo, v0.28.0 (active)
language-toml, v0.18.0 (active)
language-xml, v0.34.8 (active)
language-yaml, v0.26.0 (active)

# Dev
No dev packages
```

`

**Comment by gmist** [comment]
@White-Oak [it looks](https://github.com/AtomLinter/linter-rust/pull/66/files#diff-3ad61f393e50ad26829644bca06f82e1R37) like a copy/paste mistake

**Comment by White-Oak** [comment]
Oh, god, I'm so sorry!

**Comment by Arcanemagus** [comment]
Odd that the CI builds didn't catch this issue.
