### ISSUE TITLE
Error: EPERM: operation not permitted, write

### ISSUE THREAD

**Issue by CodeGradox** [AtomLinter/linter-rust#70]
When running the linter on a rust file I get the error `Error: EPERM: operation not permitted, write`. This happens regardless of which cargo command I choose.

I am running atom 1.9.9, windows 10 (with anniversary update), linter-rust 0.5.4 and rust 1.13.

Here is the whole error message.

> Error: EPERM: operation not permitted, write
    at Error (native)
    at Object.fs.writeSync (fs.js:706:20)
    at SyncWriteStream.write (fs.js:2064:6)
    at Object.execSync (child_process.js:519:20)
    at LinterRust.ableToJSONErrors (file:///C:/Users/Magnus/.atom/packages/linter-rust/lib/linter-rust.coffee:218:20)
    at LinterRust.ableToJSONErrors (file:///C:/Users/Magnus/.atom/packages/linter-rust/lib/linter-rust.coffee:1:1)
    at LinterRust.initCmd (file:///C:/Users/Magnus/.atom/packages/linter-rust/lib/linter-rust.coffee:202:62)
    at LinterRust.initCmd (file:///C:/Users/Magnus/.atom/packages/linter-rust/lib/linter-rust.coffee:1:1)
    at file:///C:/Users/Magnus/.atom/packages/linter-rust/lib/linter-rust.coffee:21:15
    at LinterRust.lint (file:///C:/Users/Magnus/.atom/packages/linter-rust/lib/linter-rust.coffee:19:16)
    at Object.lint (file:///C:/Users/Magnus/.atom/packages/linter-rust/lib/linter-rust.coffee:1:1)
    at promises.push.Promise.then._this.emitter.emit.linter (C:/Users/Magnus/.atom/packages/linter/lib/linter-registry.js:63:26)
    at C:/Users/Magnus/.atom/packages/linter/lib/linter-registry.js:62:23
    at Set.forEach (native)
    at LinterRegistry.lint (C:/Users/Magnus/.atom/packages/linter/lib/linter-registry.js:60:18)
    at file:///C:/Users/Magnus/.atom/packages/linter/lib/linter.coffee:98:16
    at Function.module.exports.Emitter.simpleDispatch (C:\Users\Magnus\AppData\Local\atom\app-1.9.9\resources\app.asar\node_modules\event-kit\lib\emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (C:\Users\Magnus\AppData\Local\atom\app-1.9.9\resources\app.asar\node_modules\event-kit\lib\emitter.js:125:28)
    at C:/Users/Magnus/.atom/packages/linter/lib/editor-linter.js:30:20
    at Function.module.exports.Emitter.simpleDispatch (C:\Users\Magnus\AppData\Local\atom\app-1.9.9\resources\app.asar\node_modules\text-buffer\node_modules\event-kit\lib\emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (C:\Users\Magnus\AppData\Local\atom\app-1.9.9\resources\app.asar\node_modules\text-buffer\node_modules\event-kit\lib\emitter.js:129:28)
    at TextBuffer.module.exports.TextBuffer.saveAs (C:\Users\Magnus\AppData\Local\atom\app-1.9.9\resources\app.asar\node_modules\text-buffer\lib\text-buffer.js:1156:27)
    at TextBuffer.module.exports.TextBuffer.save (C:\Users\Magnus\AppData\Local\atom\app-1.9.9\resources\app.asar\node_modules\text-buffer\lib\text-buffer.js:1126:19)
    at TextEditor.module.exports.TextEditor.save (C:\Users\Magnus\AppData\Local\atom\app-1.9.9\resources\app.asar\src\text-editor.js:755:26)
    at Pane.module.exports.Pane.saveItem (C:\Users\Magnus\AppData\Local\atom\app-1.9.9\resources\app.asar\src\pane.js:734:18)
    at Pane.saveItem (C:\Users\Magnus\AppData\Local\atom\app-1.9.9\resources\app.asar\src\pane.js:3:61)
    at Pane.module.exports.Pane.saveActiveItem (C:\Users\Magnus\AppData\Local\atom\app-1.9.9\resources\app.asar\src\pane.js:717:19)
    at Workspace.module.exports.Workspace.saveActivePaneItem (C:\Users\Magnus\AppData\Local\atom\app-1.9.9\resources\app.asar\src\workspace.js:699:35)
    at atom-workspace.commandRegistry.add.core:save (C:\Users\Magnus\AppData\Local\atom\app-1.9.9\resources\app.asar\src\register-default-commands.js:220:32)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (C:\Users\Magnus\AppData\Local\atom\app-1.9.9\resources\app.asar\src\command-registry.js:260:29)
    at C:\Users\Magnus\AppData\Local\atom\app-1.9.9\resources\app.asar\src\command-registry.js:3:61
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (C:\Users\Magnus\AppData\Local\atom\app-1.9.9\resources\app.asar\node_modules\atom-keymap\lib\keymap-manager.js:580:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (C:\Users\Magnus\AppData\Local\atom\app-1.9.9\resources\app.asar\node_modules\atom-keymap\lib\keymap-manager.js:388:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (C:\Users\Magnus\AppData\Local\atom\app-1.9.9\resources\app.asar\src\window-event-handler.js:98:36)
    at HTMLDocument.<anonymous> (C:\Users\Magnus\AppData\Local\atom\app-1.9.9\resources\app.asar\src\window-event-handler.js:3:61)

**Comment by Xudong-Huang** [comment]
the same issue

**Comment by LFalch** [comment]
I'm getting this too, on 64-bit Windows 10.

**Comment by White-Oak** [comment]
I wonder if it's windows related. Does running `rustc --version` in cmd works?

**Comment by CodeGradox** [comment]
rustup, rustc and cargo run fine for me.

**Comment by CodeGradox** [comment]
I checked on Xubuntu and I do not get the error there, so It could be windows only unless osx has the same issue.

**Comment by Maplicant** [comment]
Same issue. I'm using Windows with the anniversary update too. [This](https://github.com/electron/electron/issues/2033) seems related, it might help the developers of linter-rust.

**Comment by phsym** [comment]
Same issue. I'm running Rust 1.11 on Windows 7 (Enterprise, 64 bits, SP1), and Atom 1.9.9 with linter-rust 0.5.4

**Comment by White-Oak** [comment]
@Maplicant thanks for the linked issue! That's a little troubling: currently, linter-rust decides if it should use JSON output looking at the output of `rustc --version` and comparing version's date.
I beleive using BufferedProcess as linter does is a solution, though, it is an asynchronous function, so this will complicate a detection a bit.
Other better solution may be finding if it is possible to redirect stdout to console.log (it is probably possible).

**Comment by idan-weizman** [comment]
I think [**this**](https://discuss.atom.io/t/call-to-shell-and-get-response/20846/19) is what you are looking for.

I changed the following in the code:
`linter-rust\lib\linter-rust.coffee:218`
from:
`result = spawn.execSync rustcPath + ' --version'`
to:
`result = spawn.execSync rustcPath + ' --version', {stdio: 'pipe' }`

Tried it on my Windows 10, Rust 1.11.0, Atom 1.9.9 and it worked.
If someone can test that for Mac and Linux, to make sure it doesn't break anything, that'll be good.
